using System;
using Game.Net;
using Game.Prefabs;
using Unity.Entities;

namespace CS2MCP
{
    /// <summary>
    /// Junction control: traffic lights on/off or an all-way stop, applied to a
    /// road node through BridgeToolSystem the way the game's intersection
    /// tools apply them (node Upgraded flags regenerated by the tool pipeline).
    /// </summary>
    public sealed partial class RequestHandlers
    {
        private const CompositionFlags.General kJunctionControlFlags =
            CompositionFlags.General.TrafficLights
            | CompositionFlags.General.RemoveTrafficLights
            | CompositionFlags.General.AllWayStop;

        private BridgeResponse SetJunctionControl(BridgeRequest request)
        {
            if (!TryGetCity(out _, out BridgeResponse error))
            {
                return error;
            }
            if (!request.TryGetInt("index", out int index) || !request.TryGetInt("version", out int version))
            {
                return BridgeResponse.Error(400, "provide ?index=&version= of a junction (node) from cs2_road_graph");
            }
            if (!request.Query.TryGetValue("mode", out string mode) || string.IsNullOrEmpty(mode))
            {
                return BridgeResponse.Error(400, "provide ?mode=lights|nolights|stop|default");
            }

            var node = new Entity { Index = index, Version = version };
            if (!EntityManager.Exists(node) || !EntityManager.HasComponent<Node>(node)
                || !EntityManager.HasBuffer<ConnectedEdge>(node) || !EntityManager.HasComponent<PrefabRef>(node))
            {
                return BridgeResponse.Error(404, $"{index}:{version} is not an existing junction");
            }
            int roads = 0;
            DynamicBuffer<ConnectedEdge> edges = EntityManager.GetBuffer<ConnectedEdge>(node, isReadOnly: true);
            for (int i = 0; i < edges.Length; i++)
            {
                if (EntityManager.HasComponent<Road>(edges[i].m_Edge))
                {
                    roads++;
                }
            }
            if (roads < 3)
            {
                return BridgeResponse.Error(400, $"junction has {roads} roads; lights and stops need an intersection of 3 or more");
            }

            CompositionFlags.General add;
            switch (mode.Trim().ToLowerInvariant())
            {
                case "lights":
                    add = CompositionFlags.General.TrafficLights;
                    break;
                case "nolights":
                    add = CompositionFlags.General.RemoveTrafficLights;
                    break;
                case "stop":
                    add = CompositionFlags.General.AllWayStop;
                    break;
                case "default":
                    add = default;
                    break;
                default:
                    return BridgeResponse.Error(400, $"unknown mode '{mode}'; use lights, nolights, stop or default");
            }

            CompositionFlags flags = EntityManager.HasComponent<Upgraded>(node)
                ? EntityManager.GetComponentData<Upgraded>(node).m_Flags
                : default;
            flags.m_General = (flags.m_General & ~kJunctionControlFlags) | add;

            BridgeToolSystem tool = World.GetOrCreateSystemManaged<BridgeToolSystem>();
            if (!tool.TryQueueNodeUpgrade(node, mode.Trim().ToLowerInvariant(), flags, request))
            {
                return BridgeResponse.Error(409, "another build operation is in progress, retry shortly");
            }
            return null;
        }
    }
}
